const SHUFFLE = 'SHUFFLE';
const DEAL_ACTION = 'DEAL_ACTION';
const LOAD_NPC = 'LOAD_NPC';
const UPDATE_NPC_STATUS = 'UPDATE_NPC_STATUS';
const REMOVE_NPC = 'REMOVE_NPC';
const RESOLVE_STUN = 'RESOLVE_STUN';
const LOAD_FILE = 'LOAD_FILE';

export {SHUFFLE, DEAL_ACTION, LOAD_NPC, UPDATE_NPC_STATUS, RESOLVE_STUN, REMOVE_NPC, LOAD_FILE};