const deck = [
    { order: 49, text: "2♠" }, 
    { order: 45, text: "3♠" }, 
    { order: 41, text: "4♠" }, 
    { order: 37, text: "5♠" }, 
    { order: 33, text: "6♠" }, 
    { order: 29, text: "7♠" }, 
    { order: 25, text: "8♠" }, 
    { order: 21, text: "9♠" }, 
    { order: 17, text: "10♠" }, 
    { order: 13, text: "J♠" }, 
    { order: 9, text: "Q♠" }, 
    { order: 5, text: "K♠" }, 
    { order: 1, text: "A♠" }, 
    { order: 50, text: "2♡" }, 
    { order: 46, text: "3♡" }, 
    { order: 42, text: "4♡" }, 
    { order: 38, text: "5♡" }, 
    { order: 34, text: "6♡" }, 
    { order: 30, text: "7♡" }, 
    { order: 26, text: "8♡" }, 
    { order: 22, text: "9♡" }, 
    { order: 18, text: "10♡" }, 
    { order: 14, text: "J♡" }, 
    { order: 10, text: "Q♡" }, 
    { order: 6, text: "K♡" }, 
    { order: 2, text: "A♡" }, 
    { order: 51, text: "2♢" }, 
    { order: 47, text: "3♢" }, 
    { order: 43, text: "4♢" }, 
    { order: 39, text: "5♢" }, 
    { order: 35, text: "6♢" }, 
    { order: 31, text: "7♢" }, 
    { order: 27, text: "8♢" }, 
    { order: 23, text: "9♢" }, 
    { order: 19, text: "10♢" }, 
    { order: 15, text: "J♢" }, 
    { order: 11, text: "Q♢" }, 
    { order: 7, text: "K♢" }, 
    { order: 3, text: "A♢" }, 
    { order: 52, text: "2♣" }, 
    { order: 48, text: "3♣" }, 
    { order: 44, text: "4♣" }, 
    { order: 40, text: "5♣" }, 
    { order: 36, text: "6♣" }, 
    { order: 32, text: "7♣" }, 
    { order: 28, text: "8♣" }, 
    { order: 24, text: "9♣" }, 
    { order: 20, text: "10♣" }, 
    { order: 16, text: "J♣" }, 
    { order: 12, text: "Q♣" }, 
    { order: 8, text: "K♣" }, 
    { order: 4, text: "A♣" }, 
    { order: 53, text: "Black Joker" }, 
    { order: 0, text: "Red Joker" }
];


export default deck;